application:
  auth:
    server:
      issuer: http://localhost:9000
  rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
  jwt:
    authorization-code-ttl-ms: ${JWT_AUTHORIZATION_CODE_TTL_MS:300000}
    access-token-ttl-ms: ${JWT_ACCESS_TOKEN_TTL_MS:300000}
    refresh-token-ttl-ms: ${JWT_REFRESH_TOKEN_TTL_MS:86400000}
  cors:
    allowed-origins:
      - "http://localhost:4200"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "HEAD"
      - "OPTIONS"
    allowed-headers:
      - "authorization"
      - "accept"
      - "content-type"
      - "x-requested-with"
      - "x-xsrf-token"
    exposed-headers:
      - "x-xsrf-token"
    allow-credentials: false

server:
  port: 9000

logging:
  level:
    org.springframework.security: info

spring:
  application:
    name: authorization-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/authorization_server
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:toor}
  jpa:
    hibernate:
      ddl-auto: validate
