INSERT INTO `clients` (`id`,`client_id`,`client_id_issued_at`,`client_secret`,`client_secret_expires_at`,`client_name`,`client_authentication_methods`,`authorization_grant_types`,`redirect_uris`,`post_logout_redirect_uris`,`scopes`,`client_settings`,`token_settings`)
VALUES ('d6b26ef6-87ee-4b19-bc70-72594a74ac60','angular-client',CURRENT_TIMESTAMP,NULL,NULL,'angular-client','none','authorization_code','http://localhost:4200','http://localhost:4200','openid,profile','{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":true,"settings.client.require-authorization-consent":true}','{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');

INSERT INTO `clients` (`id`,`client_id`,`client_id_issued_at`,`client_secret`,`client_secret_expires_at`,`client_name`,`client_authentication_methods`,`authorization_grant_types`,`redirect_uris`,`post_logout_redirect_uris`,`scopes`,`client_settings`,`token_settings`)
VALUES ('88c06d81-dc94-4610-ade5-81e181b929f6','postman-client',CURRENT_TIMESTAMP,'$2y$10$HsfXWp4DvnfOzDqTVnJfxeAi7dOf5ne8e4rlg3DngBoW1NAO6gYxG',NULL,'postman-client','client_secret_basic','authorization_code,refresh_token','http://localhost:4200','http://localhost:4200','openid,profile','{"@class":"java.util.Collections$UnmodifiableMap","settings.client.require-proof-key":false,"settings.client.require-authorization-consent":true}','{"@class":"java.util.Collections$UnmodifiableMap","settings.token.reuse-refresh-tokens":true,"settings.token.x509-certificate-bound-access-tokens":false,"settings.token.id-token-signature-algorithm":["org.springframework.security.oauth2.jose.jws.SignatureAlgorithm","RS256"],"settings.token.access-token-time-to-live":["java.time.Duration",300.000000000],"settings.token.access-token-format":{"@class":"org.springframework.security.oauth2.server.authorization.settings.OAuth2TokenFormat","value":"self-contained"},"settings.token.refresh-token-time-to-live":["java.time.Duration",3600.000000000],"settings.token.authorization-code-time-to-live":["java.time.Duration",300.000000000],"settings.token.device-code-time-to-live":["java.time.Duration",300.000000000]}');

INSERT INTO `roles` (`id`,`description`,`title`) VALUES (1,'Role for admins users','Admin');

INSERT INTO `roles` (`id`,`description`,`title`) VALUES (2,'Role for normal users','User');

INSERT INTO `users` (`id`,`name`,`email`,`username`,`password`,`is_active`,`role_id`,`created_at`,`updated_at`)
VALUES (1,'Carlos Alberto Arroyo Martínez','carroyom@mail.com','carroyom','$2y$10$Tejps1b9A8oOCTGT8wB01ebx626klMvzaaBA.X7IBYAnAjqT0RFRe',b'1',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO `users` (`id`,`name`,`email`,`username`,`password`,`is_active`,`role_id`,`created_at`,`updated_at`)
VALUES (2,'Cathy Stefania Guido Rojas','cguidor@mail.com','cguidor','$2b$2y$10$Tejps1b9A8oOCTGT8wB01ebx626klMvzaaBA.X7IBYAnAjqT0RFRe',b'0',2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
